PaginaClinicaDental/app/views/auth.py
from flask import Flask , Blueprint, flash, g, redirect, render_template, request, session, url_for, jsonify
from werkzeug.security import check_password_hash, generate_password_hash

from app.models.empleado import Empleado
from app.models.rol import Rol
from app.models.servicio import Servicio
from app.models.registroCita import RegistroCita
from app.models.pago import Pago
from app.models.consultorio import Consultorio
from app.models.clinica import Clinica


import functools
from app.mensajesflash import *


from flask_login import login_user, logout_user, login_required, current_user
from app import db


auth = Blueprint("auth", __name__, url_prefix="/auth")


# Registros (BLUEPRINTS)


# /auth/register
@auth.route("/signup", methods=["GET", "POST"])
@login_required
def signup():
    consult = Consultorio.query.all()
    clinic = Clinica.query.all()
    rol = Rol.query.all()
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        passwordV = request.form.get("passwordV")
        apellidoPAtEmpleado = request.form.get("apellidoPAtEmpleado")
        apellidoMatEmpleado = request.form.get("apellidoMatEmpleado")
        correoElectronico = request.form.get("correoElectronico")
        idConsultorioEmple = request.form.get("idConsultorioEmple")
        idClinicaEmpleado = request.form.get("idClinicaEmpleado")
        tipoRol = request.form.get("tipoRol")
        estadoEmpleado = "Activo"
        creado = None

        email_exists = Empleado.query.filter_by(correoElectronico=correoElectronico).first()
        username_exists = Empleado.query.filter_by(username=username).first()

        if email_exists:
            flash('El email utilizado ya esta registrado.', category='error')
        elif username_exists:
            flash('El nombre de usuario no esta disponible.', category='error')
        elif password != passwordV:
            flash('Las contraseñas no coinciden!', category='error')
        elif len(username) < 3:
            flash('El nombre de usuario es muy corto.', category='error')
        elif len(password) < 6:
            flash('La contraseña es muy corta.', category='error')
        elif len(correoElectronico) < 6:
            flash("El correo electrónico es invalido.", category='error')
        else:
            new_user = Empleado(
                username,
                apellidoPAtEmpleado,
                apellidoMatEmpleado,
                generate_password_hash(password, method='sha256'),
                correoElectronico,
                idConsultorioEmple,
                idClinicaEmpleado,
                tipoRol,
                estadoEmpleado,
                creado,
            )

            db.session.add(new_user)
            db.session.commit()
            # Sirve para que inicie sesión de manera automatica al crear un usuario
            #login_user(new_user, remember=True)
            flash('¡Usuario creado!', category='success')
            return redirect(url_for('auth.login'))

        #return redirect(url_for('auth.login'))

    return render_template("auth/signup.html", user=current_user, consult=consult, clinic=clinic, rol=rol)


# /auth/login
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        correoElectronico = request.form.get("correoElectronico")
        password = request.form.get("password")

        user = Empleado.query.filter_by(correoElectronico=correoElectronico).first()
        if user:
            if check_password_hash(user.password, password):
                flash(LOGGED_IN, category='success')
                login_user(user, remember=True)
                return redirect(url_for('DentalShield.index'))
                #return redirect(url_for('auth.login'))
            else:
                flash(LOGIN_PASSINVALIDA, category='error')
        else:
            flash(LOGIN_USERINVALIDO, category='error')

    flash(MENSAJE_BIENVENIDA, category='success')
    return render_template("auth/login.html", user=current_user)




# Para cerrar sesión
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash(LOGOUT, category='success')
    return redirect(url_for('DentalShield.index'))

PaginaClinicaDental/app/views/clinica.py
from flask import Flask , Blueprint, flash, g, redirect, render_template, request, session, url_for, jsonify, Response
from flask_sqlalchemy import SQLAlchemy
from fpdf import FPDF
from sqlalchemy.orm import joinedload

from werkzeug.exceptions import abort
import pymysql
from flask_login import login_required, current_user
from app.mensajesflash import *


from app.models.empleado import Empleado
from app.models.rol import Rol
from app.models.servicio import Servicio
from app.models.registroCita import RegistroCita
from app.models.pago import Pago
from app.models.consultorio import Consultorio
from app.models.clinica import Clinica

import createPROCESOS as p
import functions as f

from app import db

# lazuli = Blueprint("lazuli", __name__, url_prefix="/clinica")
dentalShield = Blueprint("DentalShield", __name__,)

# Inicio del sistema web
@dentalShield.route("/")
def index():
    try:
        flash(MENSAJE_USER, category='success')
        return render_template('clinica/index.html', user=current_user)
    except Exception as ex:
        return render_template('errores/error.html', mensaje=format(ex))
    else:
        return redirect(url_for('auth.login'))
    finally:
        pass

    #return render_template('clinica/index.html', user=current_user)

#about
@dentalShield.route("/DentalShield/about")
def about():
    return render_template("clinica/about.html", user=current_user)


@dentalShield.route("/DentalShield/perfil")
@login_required
def perfil():
    if current_user.is_authenticated:
        try:
            flash(MENSAJE_USER, category='success')
            return render_template('clinica/perfil.html', user=current_user)
        except Exception as ex:
            return render_template('errores/error.html', mensaje=format(ex))
        else:
            return redirect(url_for('auth.login'))
        finally:
            pass
    #return render_template('clinica/perfil.html', user=current_user)


# Registrar un servicio
@dentalShield.route("/DentalShield/crear-servicio", methods=["GET", "POST"])
@login_required
def servicios():
    if request.method == "POST":
        nombreServicio = request.form.get("nombreServicio")
        costoServicio = request.form.get("costoServicio")

        servicio = Servicio(nombreServicio, costoServicio)

        error = None
        if not nombreServicio:
            error = "Se requiere un nombre del servicio"
        elif not costoServicio:
            error = "Se requiere un costo de servicio"
        if error is not None:
            flash(error)
        else:
            db.session.add(servicio)
            db.session.commit()
            flash(MENSAJE, category='success')
            #return redirect(url_for("DentalShield.index"))
            return redirect(url_for("DentalShield.servicios"))

    return render_template("clinica/servicios.html", user=current_user)
 

@dentalShield.route("/DentalShield/servicios-creados")

# Ver Servicios
def viewservicios():
    servicios = db.session.query(Servicio).filter(Servicio.id >= 2).all()
    flash(MENSAJE, category='success')
    return render_template("clinica/serviciosC.html", user=current_user, servicios=servicios)

#Registro de Citas
@dentalShield.route("/DentalShield/citas", methods=["GET", "POST"])
def citas():
    posts = db.session.query(Servicio).filter(Servicio.id >= 2).all() 
    servTo = Servicio.query.all()
    clinica = Clinica.query.all()
   
    if request.method == "POST":
        nombrePaciente = request.form.get("nombrePaciente")
        apellidoPatPaciente = request.form.get("apellidoPatPaciente")
        apellidoMatPaciente = request.form.get("apellidoMatPaciente")
        edad = request.form.get("edad")
        estatus = "Cita Activa"
        telefono = request.form.get("telefono")
        nota = "Sin Nota Previa"
        fecha = request.form.get("fecha")
        hora = request.form.get("hora")
        fechaCancelacion = request.form.get("fechaCancelacion") 
        idServicioRegis = request.form.get("nombreServicio")
        idServicioRegisDos = request.form.get("nombreServicio2")
        idServicioRegisTres =  request.form.get("nombreServicio3")
        idClinicaRegis = request.form.get("idClinicaRegis")
        
        fechaRegistro = fecha + " " + hora

        registro = RegistroCita(nombrePaciente, apellidoPatPaciente, apellidoMatPaciente, edad, estatus, telefono, nota, fechaRegistro, fechaCancelacion, idServicioRegis, idServicioRegisDos, idServicioRegisTres, idClinicaRegis)

        error = None
        if not nombrePaciente:
            error = "Se requiere un nombre del paciente"
        elif not apellidoPatPaciente:
            error = "Se requiere el apellido paterno del paciente"
        elif not apellidoMatPaciente:
            error = "Se requiere el apellido materno del paciente"
        elif not edad:
            error = "Se requiere la edad del paciente"
        elif not telefono:
            error = "Se requiere el teléfono del paciente"
        elif not fechaRegistro:
            error = "Se requiere una fecha de registro"

        if error is not None:
            flash(error)
        else:
            
            db.session.add(registro)
            db.session.commit()

            #CAUSA FALLAS, SOLUCIONAR!
            p.random_registroCitas(idClinicaRegis)
            p.crear_pagos()
            
            return redirect(url_for("DentalShield.printCitas"))

    return render_template("clinica/citas.html", posts=posts, clinica=clinica, user=current_user, servTo=servTo)

#Print Vista Citas
@dentalShield.route("/DentalShield/printCitas")
def printCitas():
    mydb = pymysql.Connection(host="localhost", user="root", password="root", database="clinica_dental")
    mycursor = mydb.cursor()

    mycursor.execute('SELECT MAX(id) AS id FROM registroCitas')
    lastid = mycursor.fetchone()
    idFin = lastid[0]

    ultimoReg = db.session.query(RegistroCita, Empleado, Servicio, Consultorio, Clinica 
    ).filter(
    RegistroCita.idEmpleRegis == Empleado.id,
    RegistroCita.idServicioRegis == Servicio.id,
    RegistroCita.idConsultorioReg == Consultorio.id,
    RegistroCita.idClinicaRegis == Clinica.id,
    RegistroCita.id == idFin).all()


    s2 = ('SELECT registroCitas.id, nombreServicio FROM registroCitas \
    INNER JOIN servicios ON registroCitas.idServicioRegisDos = servicios.id WHERE registroCitas.id = %s')

    s3 = ('SELECT registroCitas.id, nombreServicio FROM registroCitas \
    INNER JOIN servicios ON registroCitas.idServicioRegisTres = servicios.id WHERE registroCitas.id = %s')

    mycursor.execute(s2, (idFin,))
    servicio1 = mycursor.fetchone()

    mycursor.execute(s3, (idFin,))
    servicio2 = mycursor.fetchone()

    return render_template("clinica/printCitas.html", user=current_user, ultimoReg=ultimoReg, servicio1=servicio1, servicio2=servicio2 )


#--------------------- Cancelar Citas
@dentalShield.route("/DentalShield/cancelarcitas/<int:id>" , methods=["GET", "POST"])
@login_required
def cancelarcitas(id):
    cancita = db.session.query(RegistroCita).filter(RegistroCita.id == id).first()

    if request.method == "POST":
        updatestatus = request.form["estatus"]
        fechacan = request.form["fechaCancelacion"]


        error = None
        if not updatestatus:
            error = "Se requiere un estatus"
        elif not fechacan:
            error = "Se requiere una fecha de cancelacion"

        if error is not None:
            flash(error)
        else:
            cancita.estatus = updatestatus
            cancita.fechaCancelacion = fechacan

            db.session.add(cancita)
            db.session.commit()
            return redirect(url_for("DentalShield.viewcitas"))

    return render_template("clinica/cancelarCitas.html", user=current_user, cancita=cancita)

#--------------------- Update Registro Citas 
@dentalShield.route("/DentalShield/updatecitas/<int:id>", methods=["GET", "POST"])
@login_required
def updatecitas(id):
    posts = Servicio.query.all()
    clinica = Clinica.query.all()
    ucita = db.session.query(RegistroCita).filter(RegistroCita.id == id).first()
    
    resulCita = db.session.query(RegistroCita, Empleado, Servicio, Consultorio, Clinica 
    ).filter(RegistroCita.idEmpleRegis == Empleado.id,
    RegistroCita.idServicioRegis == Servicio.id,
    RegistroCita.idConsultorioReg == Consultorio.id,
    RegistroCita.idClinicaRegis == Clinica.id).all()

    if request.method == "POST":
        
        nombrePaciente = request.form.get("nombrePaciente")
        apellidoPatPaciente = request.form.get("apellidoPatPaciente")
        apellidoMatPaciente = request.form.get("apellidoMatPaciente")
        edad = request.form.get("edad")
        telefono = request.form.get("telefono")
        nota = request.form.get("nota")
        fechaRegistro = request.form.get("fechaRegistro")
        idClinicaRegis = request.form.get("idClinicaRegis")


        error = None
        if not nombrePaciente:
            error = "Se requiere un nombre del paciente"
        elif not apellidoPatPaciente:
            error = "Se requiere el apellido paterno del paciente"
        elif not apellidoMatPaciente:
            error = "Se requiere el apellido materno del paciente"
        elif not edad:
            error = "Se requiere la edad del paciente"
        elif not telefono:
            error = "Se requiere el teléfono del paciente"
        elif not fechaRegistro:
            error = "Se requiere una fecha de registro"

        if error is not None:
            flash(error)
        else:
            ucita.nombrePaciente = nombrePaciente
            ucita.apellidoPatPaciente = apellidoPatPaciente
            ucita.apellidoMatPaciente = apellidoMatPaciente
            ucita.edad = edad 
            ucita.telefono = telefono
            ucita.nota = nota 
            ucita.fechaRegistro = fechaRegistro
            ucita.idClinicaRegis = idClinicaRegis

            db.session.add(ucita)
            db.session.commit()

PaginaClinicaDental/app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}{% endblock %} | DENTAL SHIELD®</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/assets/dental_medical_healthcar.ico') }}">

    {% block customCSS %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/maicons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/owl-carousel/css/owl.carousel.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% endblock %}
</head>


<!-- Back to top button -->
<div class="back-to-top"></div>

<header>

    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-sm">
                    <div class="site-info">
                        <a class="mai-call text-primary"> 01 800 6589 125</a>
                        <a class="divider"> </a>
                        <a class="mai-mail text-primary"> contacto@dentalshield.com</a>
                    </div>
                </div>
            </div> <!-- .row -->
        </div> <!-- .container -->
    </div> <!-- .topbar -->

    <!-- --------------------NAV ----------------------------------------- -->
    <!-- --------------------------------------------NAV------------------------------------------------- -->

</header>

{% block body %}
{% endblock %}

<!--anuncio-->
<div class="page-section banner-home bg-image" style="background-image: url(../static/img/assets/banner-pattern.svg);">
    <div class="container py-5 py-lg-0">
        <div class="row align-items-center">
            <div class="col-lg-4 wow zoomIn">
                <div class="img-banner d-none d-lg-block">
                    <img src="{{ url_for('static', filename='img/assets/mobile_app.png')}}" alt="">
                </div>
            </div>
            <div class="col-lg-8 wow fadeInRight">
                <h1 class="font-weight-normal mb-3">¡Quedate en Casa!</h1>
                <h1 class="font-weight-normal mb-3">Es un Acto de Responsabilidad</h1>
                <a href="https://www.gob.mx/salud" target="_blank"><img
                        src="{{ url_for('static', filename='img/assets/banner_SSA.svg')}}" alt="" width="300px"
                        height="100px"></a>
                <a href="https://coronavirus.gob.mx/" class="ml-2" target="_blank"><img
                        src="{{ url_for('static', filename='img/assets/banner_covid.png')}}" alt="" width="428px"
                        height="68px"></a>
            </div>
        </div>
    </div>
</div> <!-- .banner-home -->

<footer class="page-footer">

    <div class="container">

        <div class="row px-md-3">

            <div class="col-sm-6 col-lg-3 py-3">
                <ul class="footer-menu">
                    <img src="{{ url_for('static', filename='img/assets/dental_medical_healthcar.ico')}}" alt=""
                         width="100px" height="100px"><br></ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">

                <h7>Compañía</h7>
                <ul class="footer-menu">
                    <li><a href="{{url_for('DentalShield.about')}}">Acerca de DENTAL SHIELD</a></li>
                    <li><a href="{{url_for('DentalShield.about')}}">Privacidad en DENTAL SHIELD</a></li>
                </ul>
            </div>

            <div class="col-sm-6 col-lg-3 py-3">
                <h7>Conoce más</h7>
                <ul class="footer-menu">
                    <li><a href="{{url_for('DentalShield.about')}}">Términos y Condiciones</a></li>
                    <li><a href="{{url_for('DentalShield.about')}}">Privacidad</a></li>
                    <li><a href="{{url_for('DentalShield.about')}}">Aviso legal</a></li>
                </ul>
            </div>

            <div class="col-sm-6 col-lg-3 py-3">
                <h7>Contáctanos</h7>
                <br>
                <a href="#" class="footer-link">Cuernavaca Morelos</a>
                <a href="#" class="footer-link">777-496-14-35</a>
                <a href="#" class="footer-link">contacto@dentalshield.com</a>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
                <h7 class="mt-3">DENTAL SHIELD®</h7>
                <div class="footer-sosmed mt-3">
                    <a href="#" target="_blank"><span class="mai-logo-facebook-f"></span></a>
                    <a href="#" target="_blank"><span class="mai-logo-instagram"></span></a>
                    <a href="#" target="_blank"><span class="mai-logo-twitter"></span></a>
                </div>
            </div>
        </div>

        <hr>

    </div>
</footer>
{% block customJS %}
<script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/owl-carousel/js/owl.carousel.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/wow/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/theme.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
{% endblock %}

</html>

PaginaClinicaDental/app/templates/body.html
{% extends './base.html' %}

{% block body %}
{% include './nav.html' %}
<div class="container py-3">
    {% block container %}
    <section>
        <header>{% block header %}{% endblock %}</header>
    </section>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <br/>
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong style='font-size: 14px;'>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
    {% endblock %}
</div>
{% endblock %}

PaginaClinicaDental/app/templates/nav.html
{% block customCSS %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('DentalShield.index') }}">DentalShield®</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.index') }}">Inicio</a>
            </li>
            {% if current_user.idRolEmpleado == 1 %}
            <span class="navbar-text">
                <strong>{{ current_user.username }}</strong> (Administrador)
            </span>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.perfil') }}">Perfil</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Consultas</a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item"  href="{{ url_for('DentalShield.viewservicios') }}">Consultar Servicios</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewcitas') }}">Consultar Citas</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewpagos') }}">Consultar Pagos</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viweempleados') }}">Consultar Empleados</a></li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.servicios') }}">Crear Servicios</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">Registrar Usuario</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
            </li>
            
            <!-- --------------------------------------medicos------------------------------ -->
            {% elif current_user.idRolEmpleado == 2 %}

            <span class="navbar-text">
                <strong>{{ current_user.username }}</strong> (Medico)
            </span>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.perfil') }}">Perfil</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Consultas</a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item"  href="{{ url_for('DentalShield.viewservicios') }}">Consultar Servicios</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewcitasmedicos') }}">Consultar Citas</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewpagos') }}">Consultar Pagos</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viweempleados') }}">Consultar Empleados</a></li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
            </li>
<!-- ------------- Empleado Administrativo ----------------------------------------------- -->
            {% elif current_user.idRolEmpleado == 3 %}
            <span class="navbar-text">
                <strong>{{ current_user.username }}</strong> (Asistente Administrativo)
            </span>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.perfil') }}">Perfil</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Consultas</a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item"  href="{{ url_for('DentalShield.viewservicios') }}">Consultar Servicios</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewcitas') }}">Consultar Citas</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viewpagos') }}">Consultar Pagos</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('DentalShield.viweempleados') }}">Consultar Empleados</a></li>
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
            </li>
<!-- ------------------------------------sin loggin-------------------------------------------- -->
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Iniciar sesión</a>
            </li>
            <li>
                <a class="nav-link"  href="{{ url_for('DentalShield.viewservicios') }}">Consultar Servicios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('DentalShield.citas') }}">Agendar Citas</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block customJS %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
{% endblock %}